const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const AUTH_SECRET = process.env.AUTH_SECRET || 'fillo-super-secret-2026';
function getSupabase() { const { createClient } = require('@supabase/supabase-js'); return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY); }
router.post('/signup', async (req, res) => { try { const { email, password, name } = req.body; if (!email || !password) return res.status(400).json({ error: 'Email and password required' }); const supabase = getSupabase(); const { data: existing } = await supabase.from('users').select('id').eq('email', email).single(); if (existing) return res.status(400).json({ error: 'Email already registered' }); const hash = await bcrypt.hash(password, 10); const { data: user, error } = await supabase.from('users').insert({ email, password_hash: hash, name: name || '', plan: 'trial', created_at: new Date().toISOString() }).select().single(); if (error) return res.status(500).json({ error: error.message }); const token = jwt.sign({ userId: user.id, email: user.email }, AUTH_SECRET, { expiresIn: '30d' }); res.json({ success: true, token, user: { id: user.id, email: user.email, name: user.name, plan: user.plan } }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/login', async (req, res) => { try { const { email, password } = req.body; if (!email || !password) return res.status(400).json({ error: 'Email and password required' }); const supabase = getSupabase(); const { data: user, error } = await supabase.from('users').select('*').eq('email', email).single(); if (error || !user) return res.status(401).json({ error: 'Invalid credentials' }); const valid = await bcrypt.compare(password, user.password_hash); if (!valid) return res.status(401).json({ error: 'Invalid credentials' }); const token = jwt.sign({ userId: user.id, email: user.email }, AUTH_SECRET, { expiresIn: '30d' }); res.json({ success: true, token, user: { id: user.id, email: user.email, name: user.name, plan: user.plan } }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/me', async (req, res) => { try { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'No token' }); const decoded = jwt.verify(token, AUTH_SECRET); const supabase = getSupabase(); const { data: user, error } = await supabase.from('users').select('id, email, name, plan, created_at').eq('id', decoded.userId).single(); if (error || !user) return res.status(404).json({ error: 'User not found' }); res.json({ success: true, user }); } catch (err) { res.status(401).json({ error: 'Invalid token' }); } });
module.exports = router;
