const express = require('express');
const router = express.Router();
const jwt = require('jsonwebtoken');
const AUTH_SECRET = process.env.AUTH_SECRET || 'fillo-super-secret-2026';
function getSupabase() { const { createClient } = require('@supabase/supabase-js'); return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY); }
function auth(req, res, next) { try { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'No token' }); req.user = jwt.verify(token, AUTH_SECRET); next(); } catch { res.status(401).json({ error: 'Invalid token' }); } }
router.get('/', auth, async (req, res) => { try { const supabase = getSupabase(); const { data, error } = await supabase.from('venues').select('*').eq('user_id', req.user.userId); if (error) return res.status(500).json({ error: error.message }); res.json({ success: true, venues: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/', auth, async (req, res) => { try { const { name, address, type, website, google_place_id } = req.body; if (!name) return res.status(400).json({ error: 'Venue name required' }); const supabase = getSupabase(); const { data, error } = await supabase.from('venues').insert({ user_id: req.user.userId, name, address, type, website, google_place_id, created_at: new Date().toISOString() }).select().single(); if (error) return res.status(500).json({ error: error.message }); res.json({ success: true, venue: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.put('/:id', auth, async (req, res) => { try { const supabase = getSupabase(); const { data, error } = await supabase.from('venues').update(req.body).eq('id', req.params.id).eq('user_id', req.user.userId).select().single(); if (error) return res.status(500).json({ error: error.message }); res.json({ success: true, venue: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.delete('/:id', auth, async (req, res) => { try { const supabase = getSupabase(); const { error } = await supabase.from('venues').delete().eq('id', req.params.id).eq('user_id', req.user.userId); if (error) return res.status(500).json({ error: error.message }); res.json({ success: true }); } catch (err) { res.status(500).json({ error: err.message }); } });
module.exports = router;
