const axios = require('axios');

// Webflow CMS API service
// Requires: Webflow API token + Collection ID from venue's Webflow site
// API token: Webflow Dashboard → Account Settings → Integrations → API Access

const BASE = 'https://api.webflow.com/v2';

function getHeaders(apiToken) {
  return {
    'Authorization': `Bearer ${apiToken}`,
    'Content-Type': 'application/json',
    'accept-version': '2.0.0',
  };
}

// Test connection + get site info
async function testConnection(apiToken) {
  try {
    const res = await axios.get(`${BASE}/token/authorized_by`, {
      headers: getHeaders(apiToken),
      timeout: 8000,
    });
    return { success: true, user: res.data?.email, workspaces: res.data?.workspaces?.length };
  } catch (err) {
    return { success: false, error: err.response?.data?.message || err.message };
  }
}

// Get all collections for a site
async function getCollections(apiToken, siteId) {
  try {
    const res = await axios.get(`${BASE}/sites/${siteId}/collections`, {
      headers: getHeaders(apiToken),
      timeout: 8000,
    });
    return res.data?.collections || [];
  } catch (err) {
    console.error('Webflow getCollections error:', err.message);
    return [];
  }
}

// Create a new CMS item (blog post, event, announcement)
async function createItem({ apiToken, collectionId, fields, live = false }) {
  try {
    const res = await axios.post(
      `${BASE}/collections/${collectionId}/items${live ? '/live' : ''}`,
      { fieldData: fields },
      { headers: getHeaders(apiToken), timeout: 10000 }
    );
    return {
      success: true,
      itemId: res.data?.id,
      slug: res.data?.fieldData?.slug,
      live,
    };
  } catch (err) {
    return { success: false, error: err.response?.data?.message || err.message };
  }
}

// Publish a draft item live
async function publishItem(apiToken, collectionId, itemId) {
  try {
    const res = await axios.post(
      `${BASE}/collections/${collectionId}/items/${itemId}/live`,
      {},
      { headers: getHeaders(apiToken), timeout: 8000 }
    );
    return { success: true, itemId };
  } catch (err) {
    return { success: false, error: err.response?.data?.message || err.message };
  }
}

// Main publish function — respects Pilot Mode
async function publishContent({ apiToken, collectionId, pilotMode = 'suggest', draft }) {
  if (pilotMode === 'off') {
    return { success: false, skipped: true, reason: 'Pilot Mode is OFF for this content type' };
  }

  const live = pilotMode === 'auto';

  const fields = {
    name: draft.title || 'Fillo Generated Post',
    slug: slugify(draft.title || 'fillo-post'),
    'post-body': formatContent(draft),
    'post-summary': draft.intro || draft.content?.slice(0, 150) || '',
    'published-on': new Date().toISOString(),
  };

  const result = await createItem({ apiToken, collectionId, fields, live });

  return {
    ...result,
    pilotMode,
    action: live ? 'Published live to Webflow' : 'Draft saved to Webflow CMS',
    auditEntry: {
      action: live ? 'Auto-published to Webflow' : 'Draft saved to Webflow',
      desc: `"${draft.title}" · Pilot Mode: ${pilotMode} · Live: ${live}`,
      platform: 'Webflow',
    },
  };
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function formatContent(draft) {
  const parts = [draft.intro, draft.body, draft.cta, draft.content, draft.text].filter(Boolean);
  return parts.join('\n\n') + '\n\n*Content generated by Fillo AI*';
}

module.exports = { testConnection, getCollections, createItem, publishItem, publishContent };